spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/powerpulse_db
    username: postgres
    password: "#Infinity03"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8080